source-file ~/.dotfiles/tmux/core/plugins.tmux # List of plugins
source-file ~/.dotfiles/tmux/core/config.tmux # Config file
source-file ~/.dotfiles/tmux/core/keymaps.tmux # Keymaps
source-file ~/.dotfiles/tmux/core/theme.tmux # Current theme

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
