require("nvim_conf.plugins-setup")
require("nvim_conf.core.options")
require("nvim_conf.core.keymaps")
require("nvim_conf.core.colorscheme")

require("nvim_conf.plugins.autopairs")
require("nvim_conf.plugins.comment")
require("nvim_conf.plugins.gitsigns")
require("nvim_conf.plugins.lualine")
require("nvim_conf.plugins.nvim-tree")
require("nvim_conf.plugins.telescope")
require("nvim_conf.plugins.treesitter")
require("nvim_conf.plugins.harpoon")

require("nvim_conf.plugins.lsp")
